GET http://localhost:3000/todos/
####

GET http://localhost:3000/todos/3/
####

GET http://localhost:3000/agenda/?date=2023-04-27
####

POST http://localhost:3000/todos/
Content-Type: application/json 

{
    "id": 6,
    "todo": "Finalize Event Theme",
    "priority": "LOW",
    "status": "TO DO",
    "category": "HOME",
    "dueDate" : "2023-04-27"
}

####

PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
    "status": "DONE"
}
####

DELETE http://localhost:3000/todos/3
####